#!/usr/bin/env python3
#coding=utf8

from dex import DexFile

COLOR_CATCH         = '#cc0000'
COLOR_CATCH_TEXT    = '#660000'
COLOR_SWITCH        = '#0099cc'
COLOR_SWITCH_TEXT   = '#0033cc'
COLOR_COND_OK       = '#00cc00'

if __name__ == '__main__':
	import sys
	df = DexFile(sys.argv[1])
	blocks = df.getfunc(*sys.argv[2:5])

	def escape(s):
		return s.replace('\\', '\\\\').replace('"', '\\"')

	def join(adict):
		return '[%s]' % ','.join('%s="%s"' % item for item in adict.items())

	print('digraph {')

	attrs = {}
	attrs['shape'] = 'box'
	attrs['fontname'] = 'monospace'
	print('node', join(attrs))

	# first, print all nodes
	for block in blocks:
		attrs = {}
		if block.ops:
			ins = zip(block.addrs, block.ops, block.args)
			ins = r'\l'.join('%04x: %-20s %s' % (a,o,escape(r)) for a,o,r in ins)
			attrs['label'] = block.name + r'\n\n' + ins + r'\l'
		if 'move-exception' in block.ops:
			attrs['color'] = COLOR_CATCH
		print(block.name, join(attrs))

	# then, all the edges
	for block in blocks:
		assert block.succ is not None
		for cond, target in block.succ.items():
			attrs = {}
			if type(cond) is int:
				attrs['color'] = COLOR_SWITCH
				attrs['taillabel'] = str(cond)
				attrs['labelfontcolor'] = COLOR_SWITCH_TEXT
			elif cond is True:
				attrs['color'] = COLOR_COND_OK
			print(block.name, '->', target.name, join(attrs))
		for caught, target in block.catches.items():
			attrs = {}
			attrs['color'] = COLOR_CATCH
			attrs['taillabel'] = caught
			attrs['labelfontcolor'] = COLOR_CATCH_TEXT
			print(block.name, '->', target.name, join(attrs))

	print('}')
