#!/usr/bin/env python3
#coding=utf8

from dex import DexFile, simplify
import logging
log = logging.getLogger('dex2dot')

COLOR_CATCH         = '#cc000066'
COLOR_CATCH_TEXT    = '#99000066'
COLOR_SWITCH        = '#0099cc'
COLOR_SWITCH_TEXT   = '#0033cc'
COLOR_COND_OK       = '#00cc00'

COLOR_IMPLICIT      = '#999999'

def dumpdot(func, config):
	log.info('dumping function %s...', func.name)
	blocks = func.blocks

	def esc(s):
		return s.replace('\\', '\\\\').replace('"', '\\"')

	def join(adict):
		return '[%s]' % ','.join('%s="%s"' % item for item in adict.items())

	print('digraph {')

	attrs = {}
	attrs['splines'] = 'ortho'
	attrs['ranksep'] = '2'
	print('graph', join(attrs))

	attrs = {}
	attrs['shape'] = 'box'
	attrs['fontname'] = 'monospace'
	print('node', join(attrs))

	# first, print all nodes
	log.info('  dumping blocks')
	for block in blocks:
		log.debug('    %s', block.name)
		attrs = {}
		if 'move-exception' in block.ops:
			attrs['color'] = COLOR_CATCH
		simplify(func, block, config)
		if block.ops:
			ins = zip(block.addrs, map(esc, block.ops), map(esc, block.args))
			ins = r'\l'.join('%04x: %-20s %s' % junk for junk in ins)
			attrs['label'] = block.name + r'\n\n' + ins + r'\l'
		elif block.name.startswith('func_'):
			if block.name == 'func_entry':
				# entry block
				info = block.name + r'\n'
				info += r'\nclass:     %s' % func.clazz
				info += r'\lname:      %s' % func.name
				info += r'\ltype:      %s' % func.type
				info += r'\laccess:    %s' % hex(func.access)
				info += r'\lbyte addr: %s' % hex(func.fileoff)
				info += r'\l#regs:     %d' % func.regcount
				info += r'\l#args:     %d' % func.argcount
				# function args are always last.
				for r in range(func.regcount-func.argcount, func.regcount):
					if func.locals[r]:
						v = func.locals[r][0]
						assert v.start == 0
						stuff = (r, v.name, v.type)
					else:
						# TODO: we should figure out the type from func.type
						stuff = (r, '?', '?')
					info += r'\l           v%d is %s (%s)' % stuff
				info += r'\l'
				attrs['label'] = info
			attrs['fontcolor'] = COLOR_IMPLICIT
			attrs['style'] = 'dashed'
		print(block.name, join(attrs))

	# then, all the edges
	log.info('  dumping edges')
	for block in blocks:
		assert block.succ is not None
		for cond, target in block.succ.items():
			attrs = {}
			if type(cond) is int:
				attrs['color'] = COLOR_SWITCH
				attrs['taillabel'] = str(cond)
				attrs['labelfontcolor'] = COLOR_SWITCH_TEXT
			elif cond is True:
				attrs['color'] = COLOR_COND_OK
			print(block.name, '->', target.name, join(attrs))
		for caught, target in block.catches.items():
			attrs = {}
			attrs['color'] = COLOR_CATCH
			attrs['taillabel'] = caught
			attrs['labelfontcolor'] = COLOR_CATCH_TEXT
			attrs['style'] = 'dotted'
			print(block.name, '->', target.name, join(attrs))

	print('}')

def _parseargs():
	import sys
	import argparse

	parser = argparse.ArgumentParser(
		description='Create a .dot graph from a dalvik function')

	parser.add_argument('dexpath', metavar='filepath', type=str,
		help='path to apk, jar, zip or dex file')
	parser.add_argument('clazz', metavar='class', type=str,
		help='e.g. "Ljava/lang/String;"')
	parser.add_argument('name', metavar='methodname', type=str,
		help='e.g. "replace"')
	parser.add_argument('type', metavar='methodtype', type=str,
		help='e.g. "(CC)Ljava/lang/String;"')

	parser.add_argument('-v', '--verbose', action='store_true',
		dest='verbose', help='be chatty about what we\'re doing')
	parser.add_argument('-d', '--debug', action='store_true',
		dest='debug', help='be VERY chatty about what we\'re doing')
	parser.add_argument('-s', '--simple-syntax', action='store_true',
		dest='simplify', help='rewrite some instructions in a Java-like syntax')
	parser.add_argument('-n', '--named-vars', action='store_true',
		dest='namevars', help='(only with --simple-syntax) ' +
		'replace registers with variable names where available')

	return parser.parse_args()

if __name__ == '__main__':
	args = _parseargs()

	level = logging.INFO if args.verbose else logging.WARNING
	level = logging.DEBUG if args.debug else level
	f = '%(module)-10s %(levelname)-8s %(message)s'
	logging.basicConfig(format=f, level=level)

	df = DexFile(args.dexpath)
	func = df.getfunc(args.clazz, args.name, args.type)
	dumpdot(func, args)
